import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, Check, ChevronRight, Clock3, Eye, ImagePlus, LayoutDashboard, Link as LinkIcon, LogOut, Menu, MessageCircle, Pencil, Plus, Save, Settings, Trash2, Upload, Users, X } from 'lucide-react';
import './styles.css';
import './image-overrides.css';

const seedContent = { studioName: 'HYVISION-HONGYI LABS', eyebrow: 'PORTRAIT STUDIO / NEW TAIPEI', heroTitle: '留下你最真實的樣子。', heroImage: '/images/portrait-main.jpg', introTitle: '關於工作室', intro: '我相信，好的肖像不是把人變成某個樣子，而是讓你在鏡頭前，安心地成為自己。從企劃、討論到拍攝，為每一位來到 HONGYI LABS 的人，留下自然、有質感的影像。', photographer: '張鴻毅', address: '新北市林口區忠孝路566號', phone: '0905927367', email: 'stevencguai007@gmail.com', lineId: 'LINE 官方帳號', lineUrl: 'https://line.me/ti/p/dJVHfHRu5T', instagram: 'https://www.instagram.com/ye__picture/?utm_source=qr' };
const seedPhotos = [
  { id: 1, category: '人像 Portrait', title: 'Portrait study 01', url: '/images/portrait-main.jpg' },
  { id: 2, category: '人像 Portrait', title: 'Under the trees', url: '/images/portrait-outdoor.jpg' },
  { id: 3, category: '人像 Portrait', title: 'After the rain', url: '/images/portrait-rain.jpg' },
  { id: 4, category: '形象照 Branding', title: 'In focus', url: '/images/branding-light.jpg' }
];
const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } };
function App() {
  const [admin, setAdmin] = useState(location.hash === '#admin');
  const [content, setContent] = useState(() => read('frame-content-v2', seedContent));
  const [photos, setPhotos] = useState(() => read('frame-photos-v2', seedPhotos));
  useEffect(() => localStorage.setItem('frame-content-v2', JSON.stringify(content)), [content]);
  useEffect(() => localStorage.setItem('frame-photos-v2', JSON.stringify(photos)), [photos]);
  useEffect(() => { const f = () => setAdmin(location.hash === '#admin'); addEventListener('hashchange', f); return () => removeEventListener('hashchange', f); }, []);
  return admin ? <Admin content={content} setContent={setContent} photos={photos} setPhotos={setPhotos} onExit={() => { location.hash = ''; }} /> : <Public content={content} photos={photos} onAdmin={() => { location.hash = 'admin'; }} />;
}
function Public({ content, photos, onAdmin }) {
  const [menu, setMenu] = useState(false); const [filter, setFilter] = useState('全部作品'); const [lightbox, setLightbox] = useState(null);
  const visible = filter === '全部作品' ? photos : photos.filter(p => p.category.includes(filter));
  return <div className="site"><header className="nav"><a className="brand" href="#top"><span className="brand-mark">F</span><span>{content.studioName}</span></a><nav className={menu ? 'nav-links open' : 'nav-links'}><a href="#about">關於我們</a><a href="#work">作品集</a><a href="#contact">預約拍攝</a></nav><a href={content.lineUrl} className="line-pill" target="_blank" rel="noreferrer"><MessageCircle size={16}/> LINE 聯絡</a><button className="icon-button mobile-menu" onClick={() => setMenu(!menu)}><Menu size={22}/></button></header>
    <main id="top"><section className="hero"><div className="hero-copy"><p className="eyebrow">{content.eyebrow}</p><h1>{content.heroTitle}</h1><p className="hero-sub">Portraits with a little more room to breathe.<br/>為你保留一段與自己好好相處的時間。</p><a className="text-link" href="#work">探索作品 <ArrowUpRight size={17}/></a></div><div className="hero-image"><img src={content.heroImage || photos[0]?.url} alt="首頁主視覺作品"/><span className="image-note">01 — selected image</span></div></section>
      <section className="intro section-grid" id="about"><div className="section-label">01 / ABOUT</div><div className="intro-body"><p className="display-title">{content.introTitle}</p><div className="intro-text"><p>{content.intro}</p><span className="rule"/><p className="small-note">攝影師／{content.photographer}<br/>專注於人像、個人品牌與形象照。</p></div></div></section>
      <section className="work section" id="work"><div className="work-head"><div><p className="eyebrow">02 / SELECTED WORK</p><h2>作品集</h2></div><div className="filters">{['全部作品','人像','形象照'].map(f => <button key={f} className={filter === f ? 'active' : ''} onClick={() => setFilter(f)}>{f}</button>)}</div></div><div className="gallery">{visible.map((p, i) => <button className={'gallery-card card-' + (i % 3)} key={p.id} onClick={() => setLightbox(p)}><img src={p.url} alt={p.title}/><span className="card-caption"><span>{p.title}</span><small>{p.category}</small></span></button>)}</div></section>
      <section className="contact" id="contact"><div><p className="eyebrow">03 / LET'S WORK TOGETHER</p><h2>準備好讓自己<br/><em>被好好看見</em>了嗎？</h2></div><div className="contact-action"><p>不論是個人肖像、履歷形象照，或品牌內容拍攝，歡迎告訴我們你的想法。</p><a className="contact-button" href={content.lineUrl} target="_blank" rel="noreferrer"><MessageCircle size={19}/> 透過 LINE 詢問檔期 <ArrowUpRight size={17}/></a><p className="contact-detail">{content.address}<br/>{content.phone}<br/>{content.email}<br/><a href={content.instagram} target="_blank" rel="noreferrer">Instagram</a></p></div></section>
    </main><footer><span>© {new Date().getFullYear()} {content.studioName}</span><span>Made with intention.</span><button className="admin-link" onClick={onAdmin}>管理入口</button></footer>{lightbox && <div className="lightbox" onClick={() => setLightbox(null)}><button className="close" onClick={() => setLightbox(null)}><X/></button><img src={lightbox.url} alt={lightbox.title}/><p>{lightbox.title} <small>{lightbox.category}</small></p></div>}</div>;
}
function Admin({ content, setContent, photos, setPhotos, onExit }) { const [auth, setAuth] = useState(sessionStorage.getItem('frame-auth') === 'yes'); const [tab, setTab] = useState('overview'); const [editing, setEditing] = useState(null); const [toast, setToast] = useState('');
  const notify = t => { setToast(t); setTimeout(() => setToast(''), 2200); }; if (!auth) return <Login onLogin={() => { sessionStorage.setItem('frame-auth','yes'); setAuth(true); }} />;
  const save = (next) => { setContent(next); setEditing(null); notify('資料已儲存'); };
  return <div className="admin-shell"><aside className="sidebar"><div className="admin-logo"><span className="brand-mark">F</span><div><b>{content.studioName}</b><small>STUDIO MANAGER</small></div></div><p className="side-label">工作區</p>{[['overview','總覽',LayoutDashboard],['photos','作品管理',ImagePlus],['content','網站內容',Pencil],['settings','設定',Settings]].map(([id,label,Icon]) => <button className={tab===id?'side-item selected':'side-item'} key={id} onClick={() => setTab(id)}><Icon size={18}/>{label}{id==='photos' && <span className="count">{photos.length}</span>}</button>)}<div className="sidebar-bottom"><button className="side-item" onClick={onExit}><Eye size={18}/>查看網站</button><button className="side-item muted" onClick={() => { sessionStorage.removeItem('frame-auth'); setAuth(false); }}><LogOut size={18}/>登出</button></div></aside><div className="admin-main"><header className="admin-header"><div><p className="eyebrow">STUDIO MANAGER / {tab.toUpperCase()}</p><h1>{tab==='overview'?'早安，'+content.photographer:tab==='photos'?'作品管理':tab==='content'?'網站內容':'設定'}</h1></div><div className="header-date">今天，2026 年 10 月 5 日</div></header>{tab==='overview' && <Overview photos={photos}/>} {tab==='photos' && <PhotoManager photos={photos} setPhotos={setPhotos} notify={notify}/>} {tab==='content' && <ContentManager content={content} editing={editing} setEditing={setEditing} save={save}/>} {tab==='settings' && <SettingsPanel content={content} photos={photos} setContent={setContent} notify={notify}/>} </div>{toast && <div className="toast"><Check size={17}/>{toast}</div>}</div>;
}
function Login({ onLogin }) { const [password, setPassword] = useState(''); const [error, setError] = useState(''); return <div className="login-page"><div className="login-card"><span className="brand-mark large">F</span><p className="eyebrow">PRIVATE AREA</p><h1>Studio Manager</h1><p>登入以管理你的攝影作品與網站內容。</p><label>密碼<input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&& (password==='admin' ? onLogin() : setError('密碼不正確，請再試一次。'))} placeholder="輸入管理密碼"/></label>{error&&<small className="error">{error}</small>}<button className="primary wide" onClick={() => password==='admin'?onLogin():setError('密碼不正確，請再試一次。')}>登入後台 <ChevronRight size={17}/></button><small className="demo-note">展示模式密碼：<b>admin</b></small><a href="#">← 返回網站</a></div></div> }
function Overview({ photos }) { return <div className="dashboard"><div className="metric-grid"><Metric icon={Eye} label="網站瀏覽量" value="1,284" change="+18.4%"/><Metric icon={Clock3} label="平均停留時間" value="02:48" change="+12.6%"/><Metric icon={Users} label="聯絡點擊" value="42" change="+8.1%"/><Metric icon={ImagePlus} label="作品數量" value={photos.length} change="已上架"/></div><div className="analytics-grid"><div className="panel chart-panel"><div className="panel-head"><div><h3>瀏覽趨勢</h3><p>最近 7 天的網站瀏覽量</p></div><select><option>最近 7 天</option><option>最近 30 天</option></select></div><div className="chart"><div className="y-labels"><span>400</span><span>300</span><span>200</span><span>100</span><span>0</span></div><div className="chart-area"><div className="grid-lines"/><svg viewBox="0 0 700 240" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#c9b9a5" stopOpacity=".35"/><stop offset="1" stopColor="#c9b9a5" stopOpacity="0"/></linearGradient></defs><path d="M0 190 C70 180 75 140 140 150 S190 170 235 130 S285 118 330 135 S390 90 430 110 S490 65 540 80 S610 30 700 45 L700 240 L0 240Z" fill="url(#fill)"/><path d="M0 190 C70 180 75 140 140 150 S190 170 235 130 S285 118 330 135 S390 90 430 110 S490 65 540 80 S610 30 700 45" fill="none" stroke="#8b725d" strokeWidth="3"/></svg><div className="x-labels"><span>09/29</span><span>09/30</span><span>10/01</span><span>10/02</span><span>10/03</span><span>10/04</span><span>10/05</span></div></div></div></div><div className="panel source-panel"><div className="panel-head"><div><h3>訪客來源</h3><p>訪客如何找到你</p></div><MoreDots/></div><div className="donut-wrap"><div className="donut"><b>1,284</b><span>總訪客</span></div><div className="legend"><span><i className="dot brown"/>Instagram <b>48%</b></span><span><i className="dot tan"/>Google 搜尋 <b>32%</b></span><span><i className="dot light"/>直接造訪 <b>20%</b></span></div></div></div></div><div className="panel tip-panel"><div className="tip-icon">✦</div><div><h3>一點觀察</h3><p>週末的瀏覽量比平日高出 34%，作品集中的「形象照」分類最受關注。可以考慮在週五發布新的作品。</p></div></div></div> }
function Metric({icon:Icon,label,value,change}) { return <div className="metric"><div className="metric-top"><span>{label}</span><Icon size={18}/></div><strong>{value}</strong><small className={change.includes('%')?'up':''}>{change.includes('%')?'↗ ':''}{change} <em>較上週</em></small></div> } function MoreDots(){return <span className="dots">•••</span>}
function PhotoManager({ photos, setPhotos, notify }) { const [category, setCategory] = useState('全部'); const [modal, setModal] = useState(false); const [editingId, setEditingId] = useState(null); const [draft, setDraft] = useState({title:'',category:'人像 Portrait',url:''}); const items = category==='全部'?photos:photos.filter(p=>p.category.includes(category)); const openNew = () => { setEditingId(null); setDraft({title:'',category:'人像 Portrait',url:''}); setModal(true); }; const openEdit = p => { setEditingId(p.id); setDraft({title:p.title,category:p.category,url:p.url}); setModal(true); }; const save = () => { if(!draft.title||!draft.url) return; setPhotos(editingId ? photos.map(p=>p.id===editingId?{...p,...draft}:p) : [...photos,{...draft,id:Date.now()}]); setModal(false); notify(editingId?'作品已更新':'作品已新增'); }; const upload = e => { const file=e.target.files?.[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>setDraft(d=>({...d,url:reader.result})); reader.readAsDataURL(file); }; return <div className="content-area"><div className="toolbar"><div className="tabs">{['全部','人像','形象照'].map(x=><button className={category===x?'active':''} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><button className="primary" onClick={openNew}><Plus size={17}/>新增作品</button></div><div className="admin-photo-grid">{items.map(p=><div className="admin-photo" key={p.id}><img src={p.url} alt=""/><div className="admin-photo-info"><div><b>{p.title}</b><small>{p.category}</small></div><div className="photo-actions"><button className="delete-btn" onClick={()=>openEdit(p)}><Pencil size={15}/></button><button className="delete-btn" onClick={()=>{setPhotos(photos.filter(x=>x.id!==p.id));notify('作品已刪除')}}><Trash2 size={16}/></button></div></div></div>)}</div>{modal&&<Modal title={editingId?'編輯作品':'新增作品'} close={()=>setModal(false)}><label>作品名稱<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="例如：Soft morning"/></label><label>分類<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}><option>人像 Portrait</option><option>形象照 Branding</option></select></label><label>圖片網址<input value={draft.url.startsWith('data:')?'已選擇本機圖片':draft.url} onChange={e=>setDraft({...draft,url:e.target.value})} placeholder="貼上圖片網址"/></label><label className="upload-label"><Upload size={15}/> 或選擇本機圖片<input type="file" accept="image/*" onChange={upload}/></label><button className="primary wide" onClick={save}><Save size={16}/>儲存作品</button></Modal>}</div> }
function ContentManager({ content, editing, setEditing, save }) { const keys = [['studioName','工作室名稱'],['eyebrow','首頁小標'],['heroTitle','首頁主標'],['introTitle','介紹標題'],['intro','自我介紹'],['photographer','攝影師姓名']]; const [draft,setDraft]=useState(content); return <div className="content-area"><div className="content-intro"><p className="eyebrow">CONTENT EDITOR</p><h2>編輯網站上的文字內容</h2><p>所有標示為 placeholder 的欄位，請在正式上線前替換成你的資料。</p></div><div className="editor-card">{keys.map(([key,label])=><label key={key}>{label}{key==='intro'?<textarea value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} rows="4"/>:<input value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>}</label>)}<div className="editor-actions"><button className="primary" onClick={()=>save(draft)}><Save size={16}/>儲存變更</button></div></div></div> }
function SettingsPanel({content,photos,setContent,notify}) { const [draft,setDraft]=useState(content); const selectedHero = draft.heroImage || photos[0]?.url || ''; return <div className="content-area"><div className="content-intro"><p className="eyebrow">CONTACT & INTEGRATIONS</p><h2>聯絡方式與整合設定</h2><p>這些資料會顯示在網站頁尾與預約區塊。</p></div><div className="editor-card"><label>首頁主視覺<select value={selectedHero} onChange={e=>setDraft({...draft,heroImage:e.target.value})}>{photos.map(p=><option key={p.id} value={p.url}>{p.title}／{p.category}</option>)}</select></label><label>地址<input value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></label><label>電話<input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>Email<input value={draft.email || ''} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>LINE ID<input value={draft.lineId} onChange={e=>setDraft({...draft,lineId:e.target.value})}/></label><label>LINE 官方帳號連結<input value={draft.lineUrl} onChange={e=>setDraft({...draft,lineUrl:e.target.value})}/></label><label>Instagram 連結<input value={draft.instagram} onChange={e=>setDraft({...draft,instagram:e.target.value})}/></label><div className="integration-note"><LinkIcon size={17}/><div><b>分析服務設定</b><p>目前儀表板使用展示資料。正式上線時，請在部署平台設定 GA4 Measurement ID，並將事件「LINE 點擊」與「作品開啟」送入 GA4。</p></div></div><button className="primary" onClick={()=>{setContent({...draft,heroImage:selectedHero});notify('設定已儲存')}}><Save size={16}/>儲存設定</button></div></div> }
function Modal({title,close,children}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h3>{title}</h3><button className="icon-button" onClick={close}><X size={18}/></button></div>{children}</div></div>}
createRoot(document.getElementById('root')).render(<App/>);
